OrdererOrgs:
  - Name: Orderer
    Domain: example.local
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: YDSFMalang
    Domain: ydsfmalang.example.local
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: YDSFJatim
    Domain: ydsfjatim.example.local
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
